In [6]:
# example of global pixel standardization
import numpy as np
from PIL import Image


In [7]:

load_img = Image.open('horizontalview.jpg')
print(load_img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=300x300 at 0x17103248108>


### Change the loaded image to a numpy array

In [8]:
img_pixels = np.asarray(image)
print(img_pixels)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [12]:
## Print maximum, minimum values in the pixel value

print("Minimum Value: ", img_pixels.min())
print("Maximum Value: ", img_pixels.max())



Minimum Value:  0
Maximum Value:  255


### Standardize the pixel values


In [13]:
"""
1. The pixel values in image are all integers.
After standardization, we want the output values to be in a range of 0-1. 
So, the values should be changed to float.
"""
img_pixels = img_pixels.astype('float32')

In [15]:
# calculate global mean and standard deviation
mean, std = img_pixels.mean(), img_pixels.std()
print('Mean: %.3f, Standard Deviation: %.3f' % (mean, std))


Mean: 202.587, Standard Deviation: 87.460


In [16]:
## Perform standardization by following the formula

img_pixels = (img_pixels - mean) / std

mean, std = img_pixels.mean(), img_pixels.std()

In [18]:
## Print the mean and std dev of final standardized pixel values
print('Mean: %.3f, Standard Deviation: %.3f' % (mean, std))

Mean: 0.000, Standard Deviation: 1.000


### Check the standardized pixel values

In [20]:
print(img_pixels)

[[[0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  ...
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]]

 [[0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  ...
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]]

 [[0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  ...
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]]

 ...

 [[0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  ...
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]]

 [[0.59927636 0.59927636 0.59927636]
  [0.59927636 0.59927636 0.59927636]
